<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="GitVersion.MsBuild">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="AutoFixture" />
      <PackageReference Include="NMoneys" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Domain\NVs.Budget.Domain\NVs.Budget.Domain.csproj" />
      <ProjectReference Include="..\NVs.Budget.Utilities.Expressions\NVs.Budget.Utilities.Expressions.csproj" />
    </ItemGroup>

</Project>
