import { Routes } from '@angular/router';
import { NewBudgetComponent } from './budget/new-budget/new-budget.component';
import { BudgetDetailComponent } from './budget/budget-detail/budget-detail.component';
import { ReadingSettingsComponent } from './budget/reading-settings/reading-settings.component';
import { ImportOperationsComponent } from './operations/import-operations/import-operations.component';
import { OperationsListComponent } from './operations/operations-list/operations-list.component';
import { DeleteOperationsComponent } from './operations/delete-operations/delete-operations.component';
import { RetagOperationsComponent } from './operations/retag-operations/retag-operations.component';
import { LogbookViewComponent } from './operations/logbook-view/logbook-view.component';
import { LogbookGroupComponent } from './operations/logbook-group/logbook-group.component';
import { DuplicatesListComponent } from './operations/duplicates-list/duplicates-list.component';
import { TransfersListComponent } from './operations/transfers-list/transfers-list.component';
import { IndexComponent } from './index/index.component';
import { ManualImportOperationsComponent } from './operations/manual-import-operations/manual-import-operations.component';
import { BulkChangesComponent } from './operations/bulk-changes/bulk-changes.component';
import { BudgetPlansListComponent } from './budget-plans/budget-plans-list.component';
import { BudgetPlanEditorComponent } from './budget-plans/budget-plan-editor.component';
import { BudgetPlanVarianceComponent } from './budget-plans/budget-plan-variance.component';

export const routes: Routes = [
    { path: 'budget/new', component: NewBudgetComponent },
    { path: 'budget/:budgetId/operations/import', component: ImportOperationsComponent },
    { path: 'budget/:budgetId/operations/manual-import', component: ManualImportOperationsComponent },
    { path: 'budget/:budgetId/operations/bulk-changes', component: BulkChangesComponent },
    { path: 'budget/:budgetId/operations/delete', component: DeleteOperationsComponent },
    { path: 'budget/:budgetId/operations/retag', component: RetagOperationsComponent },
    { path: 'budget/:budgetId/operations/logbook/group', component: LogbookGroupComponent },
    { path: 'budget/:budgetId/operations/logbook', component: LogbookViewComponent },
    { path: 'budget/:budgetId/operations/duplicates', component: DuplicatesListComponent },
    { path: 'budget/:budgetId/plans/new', component: BudgetPlanEditorComponent },
    { path: 'budget/:budgetId/plans/:planId/variance', component: BudgetPlanVarianceComponent },
    { path: 'budget/:budgetId/plans/:planId', component: BudgetPlanEditorComponent },
    { path: 'budget/:budgetId/plans', component: BudgetPlansListComponent },
    { path: 'budget/:budgetId/transfers', component: TransfersListComponent },
    { path: 'budget/:budgetId/operations', component: OperationsListComponent },
    { path: 'budget/:budgetId/details', component: BudgetDetailComponent },
    { path: 'budget/:budgetId/reading-settings', component: ReadingSettingsComponent },
    { path: 'budget/:budgetId', redirectTo: 'budget/:budgetId/operations', pathMatch: 'full' },
    { path: '', component: IndexComponent }
];
