// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NVs.Budget.Infrastructure.Identity.OpenIddict.Yandex.Mapping;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NVs.Budget.Infrastructure.Identity.OpenIddict.Yandex.Persistence.Migrations
{
    [DbContext(typeof(UserMappingContext))]
    partial class UserMappingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("user_mapping")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NVs.Budget.Infrastructure.Identity.OpenIddict.Yandex.Mapping.UserToOwnerMapping", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "OwnerId");

                    b.ToTable("Mappings", "user_mapping");
                });
#pragma warning restore 612, 618
        }
    }
}
