// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NVs.Budget.Infrastructure.Files.CSV.Persistence.Settings;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NVs.Budget.Infrastructure.Files.CSV.Persistence.Migrations
{
    [DbContext(typeof(SettingsContext))]
    partial class SettingsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("csv_settings")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "date_time_kind", new[] { "unspecified", "utc", "local" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "validation_condition", new[] { "equals", "not_equals" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NVs.Budget.Infrastructure.Files.CSV.Persistence.Settings.StoredCsvFileReadingSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("FileNamePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CsvFileReadingSettings", "csv_settings");
                });

            modelBuilder.Entity("NVs.Budget.Infrastructure.Files.CSV.Persistence.Settings.StoredCsvFileReadingSettings", b =>
                {
                    b.OwnsOne("NVs.Budget.Infrastructure.Files.CSV.Persistence.Settings.StoredSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("StoredCsvFileReadingSettingsId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Attributes")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CultureCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("DateTimeKind")
                                .HasColumnType("integer");

                            b1.Property<string>("EncodingName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Fields")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("StoredCsvFileReadingSettingsId");

                            b1.ToTable("CsvFileReadingSettings", "csv_settings");

                            b1.ToJson("Settings");

                            b1.WithOwner()
                                .HasForeignKey("StoredCsvFileReadingSettingsId");

                            b1.OwnsMany("NVs.Budget.Infrastructure.Files.CSV.Contracts.ValidationRule", "Validation", b2 =>
                                {
                                    b2.Property<Guid>("StoredSettingsStoredCsvFileReadingSettingsId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<int>("Condition")
                                        .HasColumnType("integer");

                                    b2.Property<string>("ErrorMessage")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Pattern")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("StoredSettingsStoredCsvFileReadingSettingsId", "Id");

                                    b2.ToTable("CsvFileReadingSettings", "csv_settings");

                                    b2.WithOwner()
                                        .HasForeignKey("StoredSettingsStoredCsvFileReadingSettingsId");
                                });

                            b1.Navigation("Validation");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
